version: 2

jobs:
  build:
    docker:
      - image: mbed/doc_builder:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    steps:
      - checkout

      - run:
          name: Validate and build documentation
          command: |
            docbuilder os-docs /tmp/artifacts --path ~/project/docs.json --github_token "$GITHUB_TOKEN"
      - run:
          name: Move images
          command: |
            cp -R ~/project/docs/images /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts
          destination: docs
